Repository cloudquery/cq-provider-template, pull requests merged in 2022-01, with the labels that each got.

#10 chore: Synced file(s) with cloudquery/.github
  .github/release.yml
  .github/workflows/add_tags.yml
  .github/workflows/golang_lint.yml
  .github/workflows/pr_title.yml
  .github/workflows/provider_lint.yml
  .github/workflows/provider_mock_test.yml
Labels: chore

#11 chore: Synced file(s) with cloudquery/.github
  .github/workflows/add_tags.yml
  .github/workflows/doc_validation.yml
  .github/workflows/mock_test.yml
  .github/workflows/pr_title.yml
  .github/workflows/release.yml
  .golangci.yml
Labels: ignore-for-release

#12 feat: All migrations as files
  docs/docs.go
  go.mod
  go.sum
  main.go
  resources/demo_resource.go
  resources/migrations/1_v0.0.1.down.sql
  resources/migrations/1_v0.0.1.up.sql
  resources/provider/migrations/postgres/1_v0.0.1.down.sql
  resources/provider/migrations/postgres/1_v0.0.1.up.sql
  resources/provider/migrations/timescale/1_v0.0.1.down.sql
  resources/provider/migrations/timescale/1_v0.0.1.up.sql
  resources/provider/provider.go
  resources/provider/provider_test.go
  tools/migrations/main.go
Labels: feat
