Repository cloudquery/cq-provider-template, pull requests merged in 2022-05, with the labels that each got.

#43 fix: Updated resources structure
  docs/tables/demo_domain_resource.md
  docs/tables/demo_table.md
  resources/demo_resource.go
  resources/provider/provider.go
  resources/services/demo/gen.hcl
  resources/services/demo/resource.go
Labels: fix

#42 chore(deps): Delete `dependabot.yml`
  .github/dependabot.yml
Labels: ignore-for-release

#49 chore: Delete .goreleaser.yml
  .goreleaser.yml
Labels: ignore-for-release

#68 chore: Fix style issues
  .golangci.yml
  client/config.go
  docs/docs.go
  resources/provider/provider.go
  resources/provider/provider_test.go
  resources/services/demo/resource.go
Labels: automerge
